spring.datasource.url=
spring.jpa.hibernate.ddl-auto=
spring.jpa.show-sql=
spring.jpa.database-platform=
spring.servlet.multipart.max-file-size=
spring.servlet.multipart.max-request-size=
server.port=


# database information
spring.datasource.username=
spring.datasource.password=

# apikey
gemini.api.key=
gemini.model=

groq.api.key=
groq.model=
text.ai.provider=


