package com.carhelper.adapter;

import com.carhelper.model.DiagnosticReport;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.stereotype.Component;

import java.util.ArrayList;
import java.util.List;

@Component
public class ApiAdapter implements AiResponseAdapter {

    private final ObjectMapper mapper = new ObjectMapper();

    @Override
    public DiagnosticReport translateResponse(String rawAiJson) {
        try {
            String aiText = extractAiText(rawAiJson);
            return buildReportFromAiText(aiText);
        } catch (Exception e) {
            throw new RuntimeException("Could not read AI report: " + e.getMessage());
        }
    }

    private String extractAiText(String rawAiJson) throws Exception {
        JsonNode rootNode = mapper.readTree(rawAiJson);
        JsonNode partsNode = rootNode.path("candidates").get(0).path("content").path("parts");

        if (!partsNode.isArray() || partsNode.isEmpty()) {
            throw new RuntimeException("AI response has no parts.");
        }

        String text = partsNode.get(0).path("text").asText();

        if (text == null || text.isBlank()) {
            throw new RuntimeException("AI response has no text.");
        }

        return text.trim();
    }

    private DiagnosticReport buildReportFromAiText(String text) throws Exception {
        String cleaned = cleanJsonText(text);

        if (cleaned.startsWith("{") && cleaned.endsWith("}")) {
            JsonNode json = mapper.readTree(cleaned);

            return new DiagnosticReport(
                    readField(json, "issueName"),
                    readField(json, "detectedProblems"),
                    readField(json, "repairSuggestion"),
                    readField(json, "estimatedCost"),
                    readField(json, "aiDisclaimer")
            );
        }

        return new DiagnosticReport(
                "AI Report",
                text,
                "",
                "",
                "This report was generated by AI and should be checked by a professional mechanic."
        );
    }

    private String readField(JsonNode json, String fieldName) {
        JsonNode field = json.path(fieldName);

        if (field.isMissingNode() || field.isNull()) {
            return "";
        }

        if (field.isArray()) {
            List<String> values = new ArrayList<>();

            for (int i = 0; i < field.size(); i++) {
                String value = field.get(i).asText();

                if (value != null && !value.isBlank()) {
                    values.add((i + 1) + ". " + value);
                }
            }

            return String.join("\n", values);
        }

        if (field.isObject()) {
            return field.toPrettyString();
        }

        return field.asText();
    }

    private String cleanJsonText(String text) {
        String cleaned = text.trim();

        if (cleaned.startsWith("```json")) {
            cleaned = cleaned.substring(7).trim();
        }

        if (cleaned.startsWith("```")) {
            cleaned = cleaned.substring(3).trim();
        }

        if (cleaned.endsWith("```")) {
            cleaned = cleaned.substring(0, cleaned.length() - 3).trim();
        }

        int firstBrace = cleaned.indexOf("{");
        int lastBrace = cleaned.lastIndexOf("}");

        if (firstBrace >= 0 && lastBrace > firstBrace) {
            cleaned = cleaned.substring(firstBrace, lastBrace + 1).trim();
        }

        return cleaned;
    }
}