name: Sync to Professor Repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    if: github.repository == 'abmoqbil/CarHelper'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Push to professor repo
        env:
          TOKEN: ${{ secrets.PROFESSOR_TOKEN }}
        run: |
          git config --global user.name "sync-bot"
          git config --global user.email "sync@github.com"

          git remote add professor https://$TOKEN@github.com/cpit252-spring-26-IT1/CarHelper.git
          git push professor main --force
  
  
